# Site settings
title: raehik learns Japanese
email: thefirstmuffinman@gmail.com
description: >
  Come help an Internet rando learn Japanese.
baseurl: ""
url: "http://jp.raehik.net"

github_username: raehik
twitter_username: raehik

# Build settings
markdown: redcarpet

# Default frontmatter
defaults:
  -
  # default to post for posts (so no need for layout: post)
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
  # ... and for drafts
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
